% Descomposición de varianza
close all;
clear;
% Carga de modelo y solución en el Workspace de Matlab u Octave
readmod02;

% Definición de Períodos iniciales y finales de pronóstico.
startpred = qq(2006,1);
endpred = qq(2018,3);

%% Descomposición de varianza
[X, Y, List, A, B] = fevd(g, ...
    startpred:endpred);

% Descomposición absoluta
var_dsc_abs = A;
% Descomposición relativa
var_dsc_rel = B;
var_dsc_s_name = List{2};


%% GRÁFICAS
% nombre de los shocks
shocks = get(g,'elist');
% Paleta de colores
col = SimTools.from_stack_exchange.distinguishable_colors(length(shocks),'b',@(x) SimTools.from_stack_exchange.colorspace('RGB->Lab',x));
%% Gráfica Inflación
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])
barcon(var_dsc_rel.v_y, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza v_y", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')

%% Gráfica Crecimiento
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])

barcon(var_dsc_rel.v_cpi, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza v_cpi", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')

%% Gráfica Tipo de Cambio Nominal
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])

barcon(var_dsc_rel.E_v_cpi, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza E_v_cpi", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')

%% Gráfica Tasa de interés de PM
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])

barcon(var_dsc_rel.i, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza i", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')

%% Gráfica Tasa de interés real
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])

barcon(var_dsc_rel.r, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza r", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')

%% Gráfica Expectativas cambiarias
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])

barcon(var_dsc_rel.E_v_s, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza E_v_s", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')

%% Gráfica Tipo de Cambio Nominal
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])

barcon(var_dsc_rel.v_s, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza v_s", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')

%% Gráfica Prima por riesgo
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])
% Paleta de colores
barcon(var_dsc_rel.prem, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza prem", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')
%% Gráfica Tipo de Cambio Real
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])
% Paleta de colores
barcon(var_dsc_rel.v_z, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza v_z", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')
%% Gráfica Inflación externa
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])
% Paleta de colores
barcon(var_dsc_rel.v_cpi_star, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza v_cpi_star", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')
%% Gráfica Tasa de interés externa
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])
% Paleta de colores
barcon(var_dsc_rel.i_star, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza i_star", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')

%% Gráfica Tasa de interés externa
figure('Position', [1 42.0181818181818 1675.63636363636 825.6])
% Paleta de colores
barcon(var_dsc_rel.v_y_star, ...
        'barWidth=', 1, ...
        'colorMap=',col, ...
        'dateFormat=','YYFP', ...
        'evenlySpread=', false);
ylim([0 1])    
title("Descomposición de varianza v_y_star", 'interpreter','none');    
legend(shocks, ...
    'Interpreter','none', ...
    'Location','bestoutside')