%{
Este deipo de gráficas contienen una tabla en la parte inferior que muestra
la información de los últimos meses o trimestres para datos históricos y
para proyecciones una ventana de tiempo razonable (por lo generar el último
datos observado más 8 trimestres de pronósticos).
%}

% Inicializamos la gráfica
figure;
set( ...
    gcf, ...
    'defaultaxesfontsize',12, ...
    'Position', [1 42.0182 1417.1 976.73] ...
    );

main_p = uipanel('Units','normalized');

% ----- Panel de gráfica -----
plot_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8, 1, 0.8], ...
    'BackgroundColor', [1, 1, 1] ...
    );

ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);

% panel
table_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
    'BackgroundColor', [1, 1, 1]);

data_table = [];
data_table(:, 1) = MODEL.PreProc.monthly.ln_ipei_mm(mm(2023,12):mm(2024,4));
data_table(:, 2) = MODEL.PreProc.monthly.ln_ipei_mm(mm(2023,12):mm(2024,4));
text_Color = [[1 0 0]; [0 0 1]];

SimTools.scripts.plot_data_table( ...
    mm(2023,12):mm(2024,4), ...
    data_table, ...
    'Parent', table_p, ...
    'SeriesNames', {'SVAR50IPEI Abr 2024', 'SVAR50IPEI Abr 2024'},...
    'TextColor', text_Color, ...
    'ColNameWidth', 0.23, ...
    'FontSize', 11 ...
    );

axis on;

plt = plot([MODEL.PreProc.monthly.ln_ipei_mm,...
    MODEL.PreProc.monthly.ln_ipei_mm],...
    'Marker', '.', ...
    'MarkerSize', 17, ...
    'LineWidth', 1.25);

legend({'SVAR50IPEI Abr 2024', 'SVAR50IPEI Abr 2024'},...
    'Location', 'Best');

% Colors
% corr actual
set(plt(1), 'color', [0 0 1]);
% corr ant
set(plt(2), 'color', [1 0 0]);

title('Índice de Precios de Importaciones EEUU',...
    strcat(dat2char(mm(2005, 1)),...
    '-',dat2char(mm(2024, 8))));
